default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: mini_jira_development

test:
  <<: *default
  database: mini_jira_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
